
export const villas = [
  {
    id: 1,
    name: "House Luna",
    location: "Chennai",
    category: "Anna Nagar",
    guests: 11,
    bedrooms: 3,
    bathrooms: 3,
    squareMeter: "400",
    rating: 4.7,
    image: "/villa9.jpg",
    dailyRent: "9000",
  },
  {
    id: 2,
    name: "House Tosco",
    location: "Chennai",
    category: "Nungampakam",
    guests: 8,
    bedrooms: 2,
    bathrooms: 2,
    squareMeter: "450",
    rating: 4.4,
    image: "/villa5.jpg",
    dailyRent: "8500",
  },
  {
    id: 3,
    name: "Rainbow Onyx",
    location: "Coimbatore",
    category: "Laxmi Mills",
    guests: 12,
    bedrooms: 2,
    bathrooms: 2,
    squareMeter: "500",
    rating: 4.9,
    image: "/villa6.jpg",
    dailyRent: "8750",
  },
  {
    id: 4,
    name: "Villa Makarska",
    location: "Italy",
    category: "Mountains",
    guests: 3,
    bedrooms: 3,
    bathrooms: 2,
    squareMeter: "750",
    rating: 5.0,
    image: "/villa4.jpg",
    dailyRent: "7555",
  },
  {
    id: 5,
    name: "Villa Boxane",
    location: "Greece",
    category: "Mountains",
    guests: 4,
    bedrooms: 5,
    bathrooms: 5,
    squareMeter: "275",
    rating: 4.0,
    image: "/villa5.jpg",
    dailyRent: "4800",
  },
  {
    id: 6,
    name: "Aphrodite",
    location: "Greece",
    category: "Seaside",
    guests: 12,
    bedrooms: 4,
    bathrooms: 2,
    squareMeter: "500",
    rating: 4.9,
    image: "/villa6.jpg",
    dailyRent: "6700",
  },
  {
    id: 7,
    name: "Villa Sunset",
    location: "Italy",
    category: "Mountains",
    guests: 15,
    bedrooms: 4,
    bathrooms: 3,
    squareMeter: "1000",
    rating: 4.8,
    image: "/villa7.jpg",
    dailyRent: "7940",
  },
  {
    id: 8,
    name: "White Lady",
    location: "Italy",
    category: "Seaside",
    guests: 25,
    bedrooms: 5,
    bathrooms: 4,
    squareMeter: "1500",
    rating: 5.0,
    image: "/villa8.jpg",
    dailyRent: "10000",
  },
  {
    id: 9,
    name: "Thebes",
    location: "Greece",
    category: "Seaside",
    guests: 5,
    bedrooms: 4,
    bathrooms: 3,
    squareMeter: "240",
    rating: 3.8,
    image: "/villa9.jpg",
    dailyRent: "9000",
  },
];

